// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOppMSb0IcfmC72WeDO6RzXuNpMsrf-Po',
    appId: '1:1021425447109:web:56127ff71eca85f46cc0ac',
    messagingSenderId: '1021425447109',
    projectId: 'flutter-prep-25de4',
    authDomain: 'flutter-prep-25de4.firebaseapp.com',
    databaseURL: 'https://flutter-prep-25de4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-25de4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0miCp2Sm_Af9qwp1WYLOlw1JYOYumICk',
    appId: '1:624054433644:android:f0b91070b297586f02e549',
    messagingSenderId: '624054433644',
    projectId: 'flutter-chat-app-c4435',
    storageBucket: 'flutter-chat-app-c4435.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_leMupQz69v5Msy78g3w1H_bIZvgEitc',
    appId: '1:624054433644:ios:505974c4961adac502e549',
    messagingSenderId: '624054433644',
    projectId: 'flutter-chat-app-c4435',
    storageBucket: 'flutter-chat-app-c4435.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDokDVyu-60-d_Ca80ZCaErByAYP6UBZXk',
    appId: '1:1021425447109:ios:ad63443a6e260a7c6cc0ac',
    messagingSenderId: '1021425447109',
    projectId: 'flutter-prep-25de4',
    databaseURL: 'https://flutter-prep-25de4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-25de4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOppMSb0IcfmC72WeDO6RzXuNpMsrf-Po',
    appId: '1:1021425447109:web:5d79bf848507876f6cc0ac',
    messagingSenderId: '1021425447109',
    projectId: 'flutter-prep-25de4',
    authDomain: 'flutter-prep-25de4.firebaseapp.com',
    databaseURL: 'https://flutter-prep-25de4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-25de4.appspot.com',
  );

}